baseURL: "https://galiishaq.github.io/"
languageCode: en-us
title: "Ishaq's blogsite" 
theme: "PaperMod"

params:
  defaultTheme: auto
  ShowCodeCopyButtons: true

  homeInfoParams:
    Title: "Hello Stranger"
    Content: Welcome to my blog. Here I will share what I learn along the way.

  socialIcons:
   -  name: github
      url: "https://github.com/galiishaq"

  ShowBreadCrumbs: True

  ShowReadingTime: True

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

menu:
  main:
    - identifier: posts
      name: Posts
      url: /
      weight: 10

    - identifier: tags
      name: Tags
      url: /tags/
      weight: 40

    - identifier: archives
      name: Archives
      url: /archives
      weight: 20
    
    - identifier: search
      name: Search
      url: /search/
      weight: 30
